import type { PanelConfig } from '@/types'

export const PANELS: PanelConfig[] = [
  { id: 'market-video', name: 'Market Video', tier: 2, enabled: false, defaultWidth: 6, defaultHeight: 4 },
  { id: 'live-markets', name: 'Live Markets', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'headlines', name: 'Headlines', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'forex', name: 'Forex', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fixed-income', name: 'Fixed Income', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'commodities', name: 'Commodities', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'crypto', name: 'Crypto', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'central-banks', name: 'Central Banks', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'economic-data', name: 'Economic Data', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'sector-heatmap', name: 'Sectors', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'market-radar', name: 'Market Radar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'correlation-engine', name: 'Correlations', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'macro-signals', name: 'Macro Signals', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'world-clock', name: 'World Clock', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'ipos-earnings', name: 'IPOs & Earnings', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'derivatives-news', name: 'Derivatives', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fintech-news', name: 'Fintech', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'regulation', name: 'Regulation', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'hedge-funds-news', name: 'Hedge Funds', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'market-analysis-news', name: 'Analysis', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'btc-etf', name: 'BTC ETF', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stablecoins', name: 'Stablecoins', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'geopolitics', name: 'Geopolitics', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'real-estate', name: 'Real Estate', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'energy', name: 'Energy', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'volatility', name: 'Volatility', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'bond-news', name: 'Bond Markets', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'predictions', name: 'Predictions', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'daily-brief', name: 'Daily Brief', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'supply-chain', name: 'Supply Chain', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'watchlist', name: 'Watchlist', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'ai-insights', name: 'AI Insights', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'export', name: 'Settings', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'earnings-calendar', name: 'Earnings Calendar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'analyst-ratings', name: 'Analyst Ratings', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'insider-trading', name: 'Insider Trading', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'economic-calendar', name: 'Economic Calendar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stock-analysis', name: 'Stock Analysis', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'trade-policy', name: 'Trade Policy', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fundamentals', name: 'Fundamentals', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stock-screener', name: 'Stock Screener', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'options-chain', name: 'Options Chain', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'crypto-markets', name: 'Crypto Markets', tier: 2, enabled: false, defaultWidth: 2, defaultHeight: 3 },
  { id: 'commodities-spot', name: 'Spot Prices', tier: 2, enabled: false, defaultWidth: 2, defaultHeight: 3 },
  { id: 'shipping-freight', name: 'Shipping & Freight', tier: 2, enabled: false, defaultWidth: 2, defaultHeight: 3 },
  { id: 'options-flow', name: 'Options Flow', tier: 2, enabled: false, defaultWidth: 2, defaultHeight: 3 },
  { id: 'short-interest', name: 'Short Interest', tier: 2, enabled: false, defaultWidth: 2, defaultHeight: 3 },
  { id: 'yield-curve', name: 'Yield Curve', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'credit-spreads', name: 'Credit Spreads', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'm2-liquidity', name: 'M2 & Liquidity', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'congress-trades', name: 'Congress Trades', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fed-watch', name: 'Fed Watch', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'pre-market', name: 'Pre/Post Market', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'social-sentiment', name: 'Social Sentiment', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'dividend-calendar', name: 'Dividend Calendar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'futures-strip', name: 'Futures Strip', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'institutional-holdings', name: 'Institutional Holdings', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'dark-pool', name: 'Dark Pool', tier: 2, enabled: false, defaultWidth: 4, defaultHeight: 3 },
  { id: 'currency-heatmap', name: 'Currency Heatmap', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'tech-analysis', name: 'Tech Analysis', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
]
