import type { PanelConfig } from '@/types'

export const PANELS: PanelConfig[] = [
  { id: 'live-markets', name: 'Live Markets', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'headlines', name: 'Headlines', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'forex', name: 'Forex', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fixed-income', name: 'Fixed Income', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'commodities', name: 'Commodities', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'crypto', name: 'Crypto', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'central-banks', name: 'Central Banks', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'economic-data', name: 'Economic Data', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'sector-heatmap', name: 'Sectors', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'market-radar', name: 'Market Radar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'correlation-engine', name: 'Correlations', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
  { id: 'macro-signals', name: 'Macro Signals', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'world-clock', name: 'World Clock', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'ipos-earnings', name: 'IPOs & Earnings', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'derivatives-news', name: 'Derivatives', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fintech-news', name: 'Fintech', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'regulation', name: 'Regulation', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'hedge-funds-news', name: 'Hedge Funds', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'market-analysis-news', name: 'Analysis', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'btc-etf', name: 'BTC ETF', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stablecoins', name: 'Stablecoins', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'geopolitics', name: 'Geopolitics', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'real-estate', name: 'Real Estate', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'energy', name: 'Energy', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'volatility', name: 'Volatility', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'bond-news', name: 'Bond Markets', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'predictions', name: 'Predictions', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'daily-brief', name: 'Daily Brief', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'supply-chain', name: 'Supply Chain', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'watchlist', name: 'Watchlist', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'ai-insights', name: 'AI Insights', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'export', name: 'Settings', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'options-flow', name: 'Options Flow', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'insider-trading', name: 'Insider Trading', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'earnings-calendar', name: 'Earnings Calendar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'analyst-ratings', name: 'Analyst Ratings', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fund-flows', name: 'Fund Flows', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'short-interest', name: 'Short Interest', tier: 2, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'economic-calendar', name: 'Economic Calendar', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stock-analysis', name: 'Stock Analysis', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'trade-policy', name: 'Trade Policy', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'fundamentals', name: 'Fundamentals', tier: 1, enabled: true, defaultWidth: 4, defaultHeight: 3 },
  { id: 'stock-screener', name: 'Stock Screener', tier: 1, enabled: true, defaultWidth: 6, defaultHeight: 4 },
]
